// <auto-generated />
using AutoKomis_ZALICZENIE.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoKomis_ZALICZENIE.Migrations
{
    [DbContext(typeof(KomisContext))]
    [Migration("20211226140609_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoKomis_ZALICZENIE.Models.KomisModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PojSil")
                        .HasColumnType("int");

                    b.Property<long>("Przebieg")
                        .HasColumnType("bigint");

                    b.Property<string>("RodzPaliwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokProd")
                        .HasColumnType("int");

                    b.Property<string>("TypNadwozia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytOglo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zdjecie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pojazdy");
                });
#pragma warning restore 612, 618
        }
    }
}
